//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodcruise.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cruceroEntities : DbContext
    {
        public cruceroEntities()
            : base("name=cruceroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categorias { get; set; }
        public virtual DbSet<jornada> jornadas { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<plato> platoes { get; set; }
        public virtual DbSet<restaurante> restaurantes { get; set; }
    }
}
