//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foodcruise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plato
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int menu { get; set; }
        public int categoria { get; set; }
    
        public virtual categoria categoria1 { get; set; }
        public virtual menu menu1 { get; set; }
    }
}
