//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public menu()
        {
            this.platoes = new HashSet<plato>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int restaurante { get; set; }
        public int jornada { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipo { get; set; }
    
        public virtual jornada jornada1 { get; set; }
        public virtual restaurante restaurante1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plato> platoes { get; set; }
    }
}
